### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by GeorgianaElena** [jupyterhub/firstuseauthenticator#26]
It would be really nice to have this fix: https://github.com/jupyterhub/firstuseauthenticator/pull/23 in TLJH :relaxed:

**Comment by consideRatio** [comment]
@yuvipanda / @minrk, can I be added as a maintainer of this on PyPI? I want to setup CD to PyPI for this as well so we can make a quick and easy release assuming we have push rights going onwards.

**Comment by willirath** [comment]
I've just added you.

**Comment by consideRatio** [comment]
I've added a PYPI_PASSWORD with a deployment token in travis, but I'm off the computer for two weeks now. If someone wants to make a release using this token, implement the pattern seen in:
- oauthenticator:
  - https://github.com/jupyterhub/oauthenticator/blob/master/.travis.yml
  - https://github.com/jupyterhub/oauthenticator/blob/master/RELEASE.md
- chartpress:
  - https://github.com/jupyterhub/chartpress/blob/master/.travis.yml
  - https://github.com/jupyterhub/chartpress/blob/master/RELEASE.md

**Comment by GeorgianaElena** [comment]
I can give it a try in the next couple of days ☃️
