### ISSUE TITLE
Enforce min passwords for users that exist, but never logged in

### ISSUE THREAD

**Issue by GeorgianaElena** [jupyterhub/firstuseauthenticator#32]
This issue was initially reported [here](https://github.com/jupyterhub/firstuseauthenticator/pull/21#issuecomment-695351009). Thanks @DongchaoChen :sunflower: 

### Proposed change

Right now, if `firstuseauthenticator.create_users` is ~~True~~ False, it's not possible to have a minimum password requirement for the users. This is because of the `_user_exists()` check here:
https://github.com/jupyterhub/firstuseauthenticator/blob/be01334bbd888a32ad330eb1fe4ba33ac9ece9ed/firstuseauthenticator/firstuseauthenticator.py#L148-L150

### Who would use this feature?

TLJH ~~enables `create_users`~~ sets `create_users` to `False` by default, so it would benefit TLJH admins that want to enforce min passwords for their users and don't want to allow anyone to login into the hub.

### (Optional): Suggest a solution

We still don't want to enforce password length requirement on existing users and lock users out of their hubs.
But we have to differentiate between existing users that have a password set and users that don't have a password (never logged in into their hub).

I believe a check similar with this one would be the way to go: https://github.com/jupyterhub/firstuseauthenticator/blob/be01334bbd888a32ad330eb1fe4ba33ac9ece9ed/firstuseauthenticator/firstuseauthenticator.py#L158-L160

**Comment by saisiddhant12** [comment]
@GeorgianaElena 
can I take this up ?
What would be the minimum password length and do we have any other constraint mentioned  over here ?

For existing set of users, we need to give notifications saying password is going to expire in n days and when they come back to reset the password, we can put these guidelines

**Comment by GeorgianaElena** [comment]
> @GeorgianaElena
can I take this up ?

Sure! That would be super nice :rocket: Thanks for offering to help @saisiddhant12  :tada: 

> What would be the minimum password length and do we have any other constraint mentioned over here ?
> For existing set of users, we need to give notifications saying password is going to expire in n days and when they come back to reset the password, we can put these guidelines

I think the issue title/description were a bit confusing, sorry about that @saisiddhant12 :confused: 
I'll do my best to explain it better.

The minimum password length feature already exists in `FirstUseAuthenticator's` latest version and was added in this PR: https://github.com/jupyterhub/firstuseauthenticator/pull/21
That PR failed to cover an use case however:

If [`firstuseauthenticator.create_users`](https://github.com/jupyterhub/firstuseauthenticator/blob/be01334bbd888a32ad330eb1fe4ba33ac9ece9ed/firstuseauthenticator/firstuseauthenticator.py#L98) is False, the users won't be created on demand, but they will have to exist in the database before they first login. This means, that when the password minimum length is checked here https://github.com/jupyterhub/firstuseauthenticator/blob/be01334bbd888a32ad330eb1fe4ba33ac9ece9ed/firstuseauthenticator/firstuseauthenticator.py#L150
it won't throw any errors because `self._user_exists(username)` will be `True` every time, because the users have to exist in the database prior their login, added by an admin user, due to the `create_users` flag.

This condition was added so that we don't lock out the users that are already in the database and might have passwords smaller that this new minimum length requirement. We still want to make sure existing users are not locked out, so in order to fix this, we have to redefine what an existing user means in this context.

A solution to this would be to don't allow passwords smaller than the `minimum_password_length` only when the user that tries to login **doesn't have a password set** already instead of only doing it when the user wasn't in the database.

Please let me know if this makes more sense @saisiddhant12:

**Comment by saisiddhant12** [comment]
Thanks for the detailing out @GeorgianaElena  
This is what I understood 

An admin user added below users 

1. user_7
2. user_8
3. user_9

and following users were already present on platform 

4. user_1
5. user_2
6. user_3 (small password violates constraint)
7. user_4
8. user_5
9. user_6 (small password violates constraint)

The ask is to adapt a design so that users like user_7, user_8, user_9 need to adhere to password rules without locking out users like user_3 and user_6

Did I get it correctly ?

**Comment by saisiddhant12** [comment]
is there a flag that signifies the user has been newly created and does not have a password ?
if no, we can create one

**Comment by GeorgianaElena** [comment]
@saisiddhant12, the snippet below checks if there's a password associated with the user trying to login:
https://github.com/jupyterhub/firstuseauthenticator/blob/be01334bbd888a32ad330eb1fe4ba33ac9ece9ed/firstuseauthenticator/firstuseauthenticator.py#L158-L160

You could use this check to also validate the password length.

**Comment by saisiddhant12** [comment]
@GeorgianaElena 
Please have a look at the PR raised above and let me know your suggestions/corrections on this

**Comment by GeorgianaElena** [comment]
Fixed by https://github.com/jupyterhub/firstuseauthenticator/pull/33 :partying_face:
